### ISSUE TITLE
problem of FairDiceLoss

### ISSUE THREAD

**Issue by 1819707238** [Harvard-Ophthalmology-AI-Lab/FairSeg#2]
你们所提出的这个FairDiceLoss似乎忘记了在文中使用？   仅在train_novel.py文件中引入并进行了定义，但似乎并未参与计算？

**Comment by tianyu0207** [comment]
> 你们所提出的这个FairDiceLoss似乎忘记了在文中使用？ 仅在train_novel.py文件中引入并进行了定义，但似乎并未参与计算？

Please run train_finetune.sh and it will call trainer_novel function and inside the function there is one line to define the FairDiceLoss here:     dice_loss = FairDiceLoss(num_classes + 1, n_attr=sens_classes, gamma=args.gamma)
