### ISSUE TITLE
limited access to your dataset

### ISSUE THREAD

**Issue by aaaaaannie** [Harvard-Ophthalmology-AI-Lab/FairSeg#3]
i have limited access to https://drive.google.com/drive/folders/1tyhEhYHR88gFkVzLkJI4gE1BoOHoHdWZ?usp=sharing. while i've sent application several times , i wondering if i can quickly get the dataset for training.

**Comment by tianyu0207** [comment]
> i have limited access to https://drive.google.com/drive/folders/1tyhEhYHR88gFkVzLkJI4gE1BoOHoHdWZ?usp=sharing. while i've sent application several times , i wondering if i can quickly get the dataset for training.

Hi have you gotten the access? If not, please feel free to send email to me: ytian11@meei.harvard.edu or to the our official lab email address: harvardopai@gmail.com
