### ISSUE TITLE
why the npz filename cannot match that in lists folder?

### ISSUE THREAD

**Issue by aaaaaannie** [Harvard-Ophthalmology-AI-Lab/FairSeg#4]

**Comment by tianyu0207** [comment]
> _No description provided._

Sorry for the confusion. You could just match the list folder with npz filename by removing the first '0' after 'data_'. For instance, change data_003998.npz to  data_03998.npz

**Comment by tianyu0207** [comment]
> _No description provided._

Sorry for the confusion. We have just fix the list folder issue. Now the npz filename should match the filename in lists folder.

**Comment by aaaaaannie** [comment]
in dataset the train code is from 1-8000,but in train.txt there is no order, so how could we pair them ?

**Comment by tianyu0207** [comment]
> in dataset the train code is from 1-8000,but in train.txt there is no order, so how could we pair them ?

it just load your list_dir files with this line  self.data_files = self.sample_list
