### ISSUE TITLE
Fail to run the training code

### ISSUE THREAD

**Issue by Tian202010** [Harvard-Ophthalmology-AI-Lab/FairSeg#5]
Has anyone run the code successfully? I have encountered several problems, many key errors.

**Comment by Tian202010** [comment]
I successfully re-implemented the gender language and ethnicity experiments. However, when it came to the race experiment, I encountered difficulties and was unable to run it-> key error: 0

**Comment by tianyu0207** [comment]
> I successfully re-implemented the gender language and ethnicity experiments. However, when it came to the race experiment, I encountered difficulties and was unable to run it-> key error: 0

Hi I have fixed the code error for race. Now it should run smoothly.

**Comment by string-ellipses** [comment]
> I successfully re-implemented the gender language and ethnicity experiments. However, when it came to the race experiment, I encountered difficulties and was unable to run it-> key error: 0
![image](https://github.com/user-attachments/assets/a0d9dcc8-4094-4cf6-8d7f-1153db0b9725)
Hello, have you ever noticed the defination of W_a in this paper? I think it is a liittle confused, According to this definition, it will assign a larger dice loss to the group, i.e., harder samples, and a smaller weight.”
