### ISSUE TITLE
more fairness datasets ?

### ISSUE THREAD

**Issue by Bobchenyx** [Harvard-Ophthalmology-AI-Lab/FairSeg#8]
Hi,

I would like to ask where can I find more datasets regarding "2D and 3D images of three different eye diseases" that you've mentioned in the content.

The link to [https://ophai.hms.harvard.edu/datasets/](https://ophai.hms.harvard.edu/datasets/) get auto redirected to [https://ophai.hms.harvard.edu/data/](https://ophai.hms.harvard.edu/data/).

Thanks

**Comment by tianyu0207** [comment]
> Hi,
> 
> I would like to ask where can I find more datasets regarding "2D and 3D images of three different eye diseases" that you've mentioned in the content.
> 
> The link to https://ophai.hms.harvard.edu/datasets/ get auto redirected to https://ophai.hms.harvard.edu/data/.
> 
> Thanks

Hi Thanks for your interest. Feel free to use this link to see all our current projects with publicly available data and codes: https://yutianyt.com/projects/
